// Copyright (c) 2025 NXP Semiconductors N.V. All rights reserved
// NXP Confidential Proprietary
// ----------------------------------------------------------------------------
// FILE NAME      : ip_xxx_3516_hs_mem_wrapper.v 
// DEPARTMENT     :  
// AUTHOR         : 
// AUTHOR'S EMAIL : 
// ----------------------------------------------------------------------------
// RELEASE HISTORY
// VERSION  DATE        AUTHOR          DESCRIPTION
// 0.1      2026-03-05  nxp             Initial Release for USB 2.0 IP 
//----------------------------------------------------------------------------
// PURPOSE  : Top module USB 2.0 IP 
// ----------------------------------------------------------------------------
// PARAMETERS
//     PARAM NAME      RANGE    : DESCRIPTION             : DEFAULT : UNITS
// e.g.DATA_WIDTH      [32:16]  : width of the data       : 32      : 
// ----------------------------------------------------------------------------

module ip_xxx_3516_hs_mem_wrapper
#(
  parameter        RAM_ADDRWIDTH = 9,
  parameter        C_NBPHYSEP = 14,
  parameter        C_SINGLE_BUFFER_SUPPORTED = 1,
  parameter        C_DOUBLE_BUFFER_SUPPORTED = 1,
  parameter        C_EPUB = 32,
  parameter        C_DAUB = 32,
  parameter        C_DALB = 17,
  parameter        C_TOGGLE_REG_READABLE = 1,
  parameter [31:0] C_EPFIFO_PAGE = 32'h00080000,
  parameter [31:0] C_DATAFIFO_PAGE = 32'h00080000
 )  
 (
				   input 		       dev_ahbs_hresetn,
				   input 		       dev_ahbs_hclk,
				   input [5:2] 		       dev_ahbs_haddr,
				   input [1:0] 		       dev_ahbs_htrans,
				   input 		       dev_ahbs_hwrite,
				   input [31:0] 	       dev_ahbs_hwdata,
				   input 		       dev_ahbs_hsel,
				   input 		       dev_ahbs_hreadyin,
				   output [31:0] 	       dev_ahbs_hrdata,
				   output 		       dev_ahbs_hreadyout,
				   output [1:0] 	       dev_ahbs_hresp,
				   input 		       host_ahbs_hresetn,
				   input 		       host_ahbs_hclk,
				   input [6:2] 		       host_ahbs_haddr,
				   input [1:0] 		       host_ahbs_htrans,
				   input 		       host_ahbs_hwrite,
				   input [31:0] 	       host_ahbs_hwdata,
				   input 		       host_ahbs_hsel,
				   input 		       host_ahbs_hreadyin,
				   output [31:0] 	       host_ahbs_hrdata,
				   output 		       host_ahbs_hreadyout,
				   output [1:0] 	       host_ahbs_hresp,
				   input 		       ahbs_dma_hresetn,
				   input 		       ahbs_dma_hclk,
				   input [RAM_ADDRWIDTH-1+5:0] ahbs_dma_haddr,
				   input [1:0] 		       ahbs_dma_htrans,
				   input 		       ahbs_dma_hwrite,
				   input [31:0]   ahbs_dma_hwdata,
				   input 		       ahbs_dma_hsel,
				   input 		       ahbs_dma_hreadyin,
				   output [31:0]  ahbs_dma_hrdata,
				   output 		       ahbs_dma_hreadyout,
				   output [1:0] 	       ahbs_dma_hresp,
				   input [2:0] 		       ahbs_dma_hsize,
				   input [2:0] 		       ahbs_dma_hburst,
				   input [63:0]   mem_q,
				   output [63:0]  mem_d,
				   output 		       mem_cs,
				   output [RAM_ADDRWIDTH-1:0]  mem_a,
				   output 		       mem_web_out,
				   output [63:0]  mem_bsel,
				   output 		       dev_usb_int_req_irq,
				   output 		       dev_usb_Int_req_fiq,
				   output 		       dev_usbframetoggle,
				   output 		       host_usb_int_req_irq,
				   input 		       USB_VBus,
				   output 		       vbuscomp_on,
				   output 		       chrgvbus,
				   output 		       dischrgvbus,
				   input 		       avalid,
				   input 		       sessend,
				   input 		       utmi_clk,
				   input [7:0] 		       utmi_rxdata,
				   input 		       utmi_rxvalid,
				   input 		       utmi_rxactive,
				   input 		       utmi_rxerror,
				   output [7:0] 	       utmi_txdata,
				   output 		       utmi_txvalid,
				   input 		       utmi_txready,
				   output 		       utmi_reset,
				   output 		       utmi_suspendm,
				   output [1:0] 	       utmi_xcvrselect,
				   output 		       utmi_termselect,
				   output [1:0] 	       utmi_opmode,
				   input [1:0] 		       utmi_linestate,
				   output [3:0] 	       utmi_vcontrol,
				   output 		       utmi_vcontrolloadm,
				   input [7:0] 		       utmi_vstatus,
				   input 		       utmi_hostdisconnect,
				   output 		       utmi_id_enable,
				   input 		       utmi_id_value,
				   output 		       utmi_dppulldown,
				   output 		       utmi_dmpulldown,
				   output 		       pdcom,
				   input 		       ulpi_clk,
				   input [7:0] 		       ulpi_rxdata,
				   output [7:0] 	       ulpi_txdata,
				   output 		       ulpi_txenable,
				   input 		       ulpi_dir,
				   output 		       ulpi_stp,
				   input 		       ulpi_nxt,
				   input 		       ulpi_ddr_sel,
				   output 		       dev_usb_needclk,
				   output 		       host_usb_needclk,
				   input 		       dev_sys_donotwakeup_n,
				   input 		       host_sys_donotwakeup_n,
				   input 		       dev_sys_wakeup_n,
				   input 		       dev_sys_utmi_clkin_lock,
				   input 		       host_sys_utmi_clkin_lock,
				   input 		       host_usb_overcurrent_n,
				   output [1:0] 	       host_usb_portindicator,
				   output 		       host_usb_portpower,
				   input [6:0] 		       token_length_counter,
				   output [6:0] 	       usb_token_length
				   );

   ip_xxx_3516_hs_mem #(
      .AHB_DATAWIDTH(32),
      .RAM_DATAWIDTH(64),
      .RAM_ADDRWIDTH(RAM_ADDRWIDTH),

      .C_NBPHYSEP(C_NBPHYSEP),
      .C_EPUB(C_EPUB),
      .C_DAUB(C_DAUB),
      .C_DALB(C_DALB),
      .C_PORTPOWER_CONTROL(1),
      .C_PORTINDICATOR(1),
      .C_EPFIFO_PAGE(C_EPFIFO_PAGE),
      .C_DATAFIFO_PAGE(C_DATAFIFO_PAGE),
      .C_SINGLE_BUFFER_SUPPORTED(C_SINGLE_BUFFER_SUPPORTED),
      .C_DOUBLE_BUFFER_SUPPORTED(C_DOUBLE_BUFFER_SUPPORTED),
      .C_TOGGLE_REG_READABLE(C_TOGGLE_REG_READABLE),
      .C_PLL_ENABLE(0),
      .C_PLL_DIVIDER(7'b0010100),
      .C_ULPI_SUPPORT(1),
      .C_UTMI_SUPPORT(1),
      .C_EXTEND_TX_DELAY(1)
   ) uut (
			   .dev_ahbs_hresetn(dev_ahbs_hresetn),
			   .dev_ahbs_hclk(dev_ahbs_hclk),
			   .dev_ahbs_haddr(dev_ahbs_haddr),
			   .dev_ahbs_htrans(dev_ahbs_htrans),
			   .dev_ahbs_hwrite(dev_ahbs_hwrite),
			   .dev_ahbs_hwdata(dev_ahbs_hwdata),
			   .dev_ahbs_hsel(dev_ahbs_hsel),
			   .dev_ahbs_hreadyin(dev_ahbs_hreadyin),
			   .dev_ahbs_hrdata(dev_ahbs_hrdata),
			   .dev_ahbs_hreadyout(dev_ahbs_hreadyout),
			   .dev_ahbs_hresp(dev_ahbs_hresp),
			   .host_ahbs_hresetn(host_ahbs_hresetn),
			   .host_ahbs_hclk(host_ahbs_hclk),
			   .host_ahbs_haddr(host_ahbs_haddr),
			   .host_ahbs_htrans(host_ahbs_htrans),
			   .host_ahbs_hwrite(host_ahbs_hwrite),
			   .host_ahbs_hwdata(host_ahbs_hwdata),
			   .host_ahbs_hsel(host_ahbs_hsel),
			   .host_ahbs_hreadyin(host_ahbs_hreadyin),
			   .host_ahbs_hrdata(host_ahbs_hrdata),
			   .host_ahbs_hreadyout(host_ahbs_hreadyout),
			   .host_ahbs_hresp(host_ahbs_hresp),
			   .ahbs_dma_hresetn(ahbs_dma_hresetn),
			   .ahbs_dma_hclk(ahbs_dma_hclk),
			   .ahbs_dma_haddr(ahbs_dma_haddr),
			   .ahbs_dma_htrans(ahbs_dma_htrans),
			   .ahbs_dma_hwrite(ahbs_dma_hwrite),
			   .ahbs_dma_hwdata(ahbs_dma_hwdata),
			   .ahbs_dma_hsel(ahbs_dma_hsel),
			   .ahbs_dma_hreadyin(ahbs_dma_hreadyin),
			   .ahbs_dma_hrdata(ahbs_dma_hrdata),
			   .ahbs_dma_hreadyout(ahbs_dma_hreadyout),
			   .ahbs_dma_hresp(ahbs_dma_hresp),
			   .ahbs_dma_hsize(ahbs_dma_hsize),
			   .ahbs_dma_hburst(ahbs_dma_hburst),
			   .mem_q(mem_q),
			   .mem_d(mem_d),
			   .mem_cs(mem_cs),
			   .mem_a(mem_a),
			   .mem_web_out(mem_web_out),
			   .mem_bsel(mem_bsel),
			   .dev_usb_int_req_irq(dev_usb_int_req_irq),
			   .dev_usb_Int_req_fiq(dev_usb_Int_req_fiq),
			   .dev_usbframetoggle(dev_usbframetoggle),
			   .host_usb_int_req_irq(host_usb_int_req_irq),
			   .USB_VBus(USB_VBus),
			   .vbuscomp_on(vbuscomp_on),
			   .chrgvbus(chrgvbus),
			   .dischrgvbus(dischrgvbus),
			   .avalid(avalid),
			   .sessend(sessend),
			   .utmi_clk(utmi_clk),
			   .utmi_rxdata(utmi_rxdata),
			   .utmi_rxvalid(utmi_rxvalid),
			   .utmi_rxactive(utmi_rxactive),
			   .utmi_rxerror(utmi_rxerror),
			   .utmi_txdata(utmi_txdata),
			   .utmi_txvalid(utmi_txvalid),
			   .utmi_txready(utmi_txready),
			   .utmi_reset(utmi_reset),
			   .utmi_suspendm(utmi_suspendm),
			   .utmi_xcvrselect(utmi_xcvrselect),
			   .utmi_termselect(utmi_termselect),
			   .utmi_opmode(utmi_opmode),
			   .utmi_linestate(utmi_linestate),
			   .utmi_vcontrol(utmi_vcontrol),
			   .utmi_vcontrolloadm(utmi_vcontrolloadm),
			   .utmi_vstatus(utmi_vstatus),
			   .utmi_hostdisconnect(utmi_hostdisconnect),
			   .utmi_id_enable(utmi_id_enable),
			   .utmi_id_value(utmi_id_value),
			   .utmi_dppulldown(utmi_dppulldown),
			   .utmi_dmpulldown(utmi_dmpulldown),
			   .pdcom(pdcom),
			   .ulpi_clk(ulpi_clk),
			   .ulpi_rxdata(ulpi_rxdata),
			   .ulpi_txdata(ulpi_txdata),
			   .ulpi_txenable(ulpi_txenable),
			   .ulpi_dir(ulpi_dir),
			   .ulpi_stp(ulpi_stp),
			   .ulpi_nxt(ulpi_nxt),
			   .ulpi_ddr_sel(ulpi_ddr_sel),
			   .dev_usb_needclk(dev_usb_needclk),
			   .host_usb_needclk(host_usb_needclk),
			   .dev_sys_donotwakeup_n(dev_sys_donotwakeup_n),
			   .host_sys_donotwakeup_n(host_sys_donotwakeup_n),
			   .dev_sys_wakeup_n(dev_sys_wakeup_n),
			   .dev_sys_utmi_clkin_lock(dev_sys_utmi_clkin_lock),
			   .host_sys_utmi_clkin_lock(host_sys_utmi_clkin_lock),
			   .host_usb_overcurrent_n(host_usb_overcurrent_n),
			   .host_usb_portindicator(host_usb_portindicator),
			   .host_usb_portpower(host_usb_portpower),
			   .token_length_counter(token_length_counter),
			   .usb_token_length(usb_token_length),
			   .usb_host_pie_INTER_PACKET_DELAY_LS_param(8'd0),
			   .usb_host_pie_INTER_PACKET_DELAY_FS_param(8'd0),
			   .usb_host_pie_INTER_PACKET_DELAY_HS_param(8'd0),
			   .usb_host_pie_PACKET_TURNAROUND_TIMEOUT_LS_param(11'd0),
			   .usb_host_pie_PACKET_TURNAROUND_TIMEOUT_FS_param(8'd0),
			   .usb_host_pie_PACKET_TURNAROUND_TIMEOUT_HS_param(8'd0),
			   .usb_host_pie_PACKET_EVENT_TIMEOUT_LS_param(13'd0),
			   .usb_host_pie_PACKET_EVENT_TIMEOUT_FS_param(9'd0),
			   .usb_host_pie_PACKET_EVENT_TIMEOUT_HS_param(9'd0),
			   .usb_host_pie_portl1l2suspend_use_sync_n(1'b0),
			   .usb_pie_INTER_PACKET_DELAY_FS_param(5'd0),
			   .usb_pie_INTER_PACKET_DELAY_HS_param(5'd0),
			   .usb_pie_PACKET_TURNAROUND_TIMEOUT_FS_param(8'd0),
			   .usb_pie_PACKET_TURNAROUND_TIMEOUT_HS_param(8'd0),
			   .usb_pie_PACKET_EVENT_TIMEOUT_FS_param(9'd0),
			   .usb_pie_PACKET_EVENT_TIMEOUT_HS_param(9'd0),
			   .async_disable(1'b0),
			   .testmode(1'b0)
			   );


endmodule

